-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 10:33:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `birthdate` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`credentials` (
  `idcredentials` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `idcustomer` INT NOT NULL,
  PRIMARY KEY (`idcredentials`, `idcustomer`),
  INDEX `fk_credentials_customer_idx` (`idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_credentials_customer`
    FOREIGN KEY (`idcustomer`)
    REFERENCES `bank`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`card` (
  `idcard` VARCHAR(16) NOT NULL,
  `pin` VARCHAR(255) NOT NULL,
  `idcustomer` INT NOT NULL,
  PRIMARY KEY (`idcard`),
  INDEX `fk_card_customer1_idx` (`idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_card_customer1`
    FOREIGN KEY (`idcustomer`)
    REFERENCES `bank`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(10,2) NOT NULL,
  `credit` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`customer_has_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`customer_has_account` (
  `idcustomer` INT NOT NULL,
  `idaccount` INT NOT NULL,
  PRIMARY KEY (`idcustomer`, `idaccount`),
  INDEX `fk_customer_has_account_account1_idx` (`idaccount` ASC) VISIBLE,
  INDEX `fk_customer_has_account_customer1_idx` (`idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_customer_has_account_customer1`
    FOREIGN KEY (`idcustomer`)
    REFERENCES `bank`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_account_account1`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bank`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`card_has_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`card_has_account` (
  `idcard` VARCHAR(16) NOT NULL,
  `idaccount` INT NOT NULL,
  INDEX `fk_card_has_account_account1_idx` (`idaccount` ASC) VISIBLE,
  INDEX `fk_card_has_account_card1_idx` (`idcard` ASC) VISIBLE,
  CONSTRAINT `fk_card_has_account_card1`
    FOREIGN KEY (`idcard`)
    REFERENCES `bank`.`card` (`idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_has_account_account1`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bank`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`withdrawal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`withdrawal` (
  `idwithdrawal` INT NOT NULL AUTO_INCREMENT,
  `idaccount` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`idwithdrawal`),
  INDEX `fk_transactions_account1_idx` (`idaccount` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_account1`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bank`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
