#ifndef CUSTOMERTESTS_GLOBAL_H
#define CUSTOMERTESTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUSTOMERTESTS_LIBRARY)
#define CUSTOMERTESTS_EXPORT Q_DECL_EXPORT
#else
#define CUSTOMERTESTS_EXPORT Q_DECL_IMPORT
#endif

#endif // CUSTOMERTESTS_GLOBAL_H
